name: Bump Version Tag and Create Release
on:
    push:
        branches:
            - master

jobs:
    build:
        name: Bump Version Tag and Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master
            - name: Bump version and push tag
              uses: mathieudutour/github-tag-action@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  default_bump: major
